let express=require("express")
const { login, reg, penemp, updst } = require("../Controllers/usercon")
const { getprods, addprod, upload, getprod, upddet, updimg, del, addcmt, ser, fil } = require("../Controllers/prodcon")
const { addcart, getcart, inc, dec } = require("../Controllers/cartcon")
let rt=express.Router()
rt.post("/login",login)
rt.post("/reg",reg)
rt.get("/getprods",getprods)
rt.post("/addprod", upload.single("img"), addprod);
rt.get("/getprod/:pid",getprod)
rt.post("/upddet",upddet)
rt.post("/updimg", upload.single("img"),updimg)
rt.get("/del/:pid",del)
rt.get("/penemp",penemp)
rt.post("/updst",updst)
rt.post("/addcmt",addcmt)
rt.post("/addcart",addcart)
rt.get("/getcart/:uid",getcart)
rt.get("/inc/:_id",inc)
rt.get("/dec/:_id",dec)
rt.post("/ser",ser)
rt.post("/fil",fil)
module.exports=rt